# Generated by Django 3.2.3 on 2021-08-27 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dropdown', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Programming',
            new_name='Country',
        ),
        migrations.RenameModel(
            old_name='Course',
            new_name='State',
        ),
    ]
