# Generated by Django 3.2.3 on 2021-08-27 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dropdown', '0002_auto_20210827_2352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='programming',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='name',
            new_name='state',
        ),
    ]
